### ISSUE TITLE
Error in linux install

### ISSUE THREAD

**Issue by fra589** [fra589/cn5X#35]
### Discussed in https://github.com/fra589/cn5X/discussions/34

<div type='discussions-op-text'>

<sup>Originally posted by **FKLCo** January 27, 2022</sup>
hallo sir
I install cn5X without problem, but when I try to run I receive the follwing error:
```
catalin@catalin-ThinkPad-X201:~$ '/home/catalin/Descărcări/cn5X-master/cn5X.py' 
qt5ct: using qt5ct plugin
cn5X++ v0.8.6 running from: /home/catalin/Descărcări/cn5X-master

                ####### #     #
  ####   #    # #        #   #     #       #
 #    #  ##   # #         # #      #       #
 #       # #  #  #####     #     #####   #####
 #       #  # #       #   # #      #       #
 #    #  #   ## #     #  #   #     #       #
  ####   #    #  #####  #     #

qt5ct: D-Bus global menu: no
Traceback (most recent call last):
  File "/home/catalin/Descărcări/cn5X-master/cn5X.py", line 2757, in <module>
    window = winMain()
  File "/home/catalin/Descărcări/cn5X-master/cn5X.py", line 170, in __init__
    self.setTranslator(langue)
  File "/home/catalin/Descărcări/cn5X-master/cn5X.py", line 2681, in setTranslator
    self.log(logSeverity.error.value, self.tr("Locale ({}) not usable, using default to english").format(locale.name()))
AttributeError: module 'locale' has no attribute 'name'
```

Linux Mint 20 Ulyana pe 64 de biți
Linux 5.4.0-96-generic x86_64
Default computer language - Romanian
Thanks for any advice.</div>

**Comment by fra589** [comment]
Oups !
It's a bug when the local language is not available in i18n.  
This bug is coming from a copy/paste mystake... 
  
Correction pushed now in new 0.8.7 version.  
  
@++;  
Gauthier.
